---
#update repositories
- apt: update_cache=yes

#apt-get dist-upgrade
- apt: upgrade=dist

- name: Copy finalizing script
  action: template src=finalizing_srv1.j2 dest=/home/{{ LOCALUSER }}/finalizing_srv1 owner=root group=root mode=0777

- name: Copy finalizing script
  action: template src=finalizing_srv2.j2 dest=/home/{{ LOCALUSER }}/finalizing_srv2 owner=root group=root mode=0777

